apiVersion: v2
name: loventure
description: Umbrella chart for Loventure MSA application

type: application

version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: gateway
    version: "0.1.0"
    repository: "file://charts/gateway"
  - name: auth-service
    version: "0.1.0"
    repository: "file://charts/auth-service"
  - name: content-service
    version: "0.1.0"
    repository: "file://charts/content-service"
  - name: course-service
    version: "0.1.0"
    repository: "file://charts/course-service"
  - name: ai-service
    version: "0.1.0"
    repository: "file://charts/ai-service"
